In [1]:
import pandas as pd
from pathlib import Path

In [2]:
caminho_arquivo = Path("..") / "DadosBrutos" / "V_EXPORTACAO.csv"

In [3]:
df = pd.read_csv(caminho_arquivo, sep=';', encoding='utf-8-sig')

colunas_texto = ['Países', 'Descrição NCM', 'UF do Produto']
for col in colunas_texto:
    df[col] = df[col].str.replace(r'[\r\n]+', ' ', regex=True).str.strip()

In [4]:
df.head(10)

,Ano,Países,Código NCM,Descrição NCM,UF do Produto,Valor US$ FOB
0,2024,Angola,17019900,"Outros açúcares de cana, beterraba, sacarose q...",São Paulo,69415459
1,2024,Angola,17019900,"Outros açúcares de cana, beterraba, sacarose q...",Pernambuco,14077098
2,2024,Angola,17019900,"Outros açúcares de cana, beterraba, sacarose q...",Minas Gerais,12952115
3,2024,Angola,17019900,"Outros açúcares de cana, beterraba, sacarose q...",Alagoas,11732058
4,2024,Cabo Verde,17019900,"Outros açúcares de cana, beterraba, sacarose q...",São Paulo,7383670
5,2024,Angola,17019900,"Outros açúcares de cana, beterraba, sacarose q...",Mato Grosso,1914447
6,2024,São Tomé e Príncipe,17019900,"Outros açúcares de cana, beterraba, sacarose q...",São Paulo,1391228
7,2024,Angola,17019900,"Outros açúcares de cana, beterraba, sacarose q...",Goiás,1162085
8,2024,Cabo Verde,17019900,"Outros açúcares de cana, beterraba, sacarose q...",Goiás,1073162
9,2024,Guiné-Bissau,17019900,"Outros açúcares de cana, beterraba, sacarose q...",São Paulo,544427

In [5]:
print(df.shape)

(1576, 6)

In [6]:
colunas = ['Ano', 'UF do Produto', 'Código NCM', 'Descrição NCM', 'Valor US$ FOB', 'Países']
angola = df.loc[df['Países'] == 'Angola', colunas]

pd.set_option('display.max_rows', None)   
angola.sort_values('Valor US$ FOB', ascending=False)

,Ano,UF do Produto,Código NCM,Descrição NCM,Valor US$ FOB,Países
1012,2017,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",136027749,Angola
1418,2014,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",128569913,Angola
745,2019,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",100076543,Angola
892,2018,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",88603079,Angola
327,2022,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",88017461,Angola
1170,2016,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",87207279,Angola
0,2024,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",69415459,Angola
1298,2015,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",66212629,Angola
585,2020,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",53716172,Angola
460,2021,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",36231275,Angola
165,2023,São Paulo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",30786903,Angola
1013,2017,Paraná,17019900,"Outros açúcares de cana, beterraba, sacarose q...",24016578,Angola
1171,2016,Pernambuco,17019900,"Outros açúcares de cana, beterraba, sacarose q...",23306239,Angola
1014,2017,Pernambuco,17019900,"Outros açúcares de cana, beterraba, sacarose q...",21502316,Angola
1419,2014,Pernambuco,17019900,"Outros açúcares de cana, beterraba, sacarose q...",14100512,Angola
1,2024,Pernambuco,17019900,"Outros açúcares de cana, beterraba, sacarose q...",14077098,Angola
2,2024,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",12952115,Angola
328,2022,Pernambuco,17019900,"Outros açúcares de cana, beterraba, sacarose q...",12593151,Angola
3,2024,Alagoas,17019900,"Outros açúcares de cana, beterraba, sacarose q...",11732058,Angola
1420,2014,Paraná,17019900,"Outros açúcares de cana, beterraba, sacarose q...",11134859,Angola
1015,2017,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",9797589,Angola
746,2019,Pernambuco,17019900,"Outros açúcares de cana, beterraba, sacarose q...",8913208,Angola
1421,2014,Não Declarada,17019900,"Outros açúcares de cana, beterraba, sacarose q...",8550741,Angola
1422,2014,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",7845615,Angola
1299,2015,Paraná,17019900,"Outros açúcares de cana, beterraba, sacarose q...",7135699,Angola
586,2020,Pernambuco,17019900,"Outros açúcares de cana, beterraba, sacarose q...",6916294,Angola
329,2022,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",5918913,Angola
747,2019,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",4377546,Angola
1300,2015,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",4166977,Angola
1424,2014,Alagoas,17019900,"Outros açúcares de cana, beterraba, sacarose q...",3900793,Angola
1425,2014,Mato Grosso do Sul,17019900,"Outros açúcares de cana, beterraba, sacarose q...",3581367,Angola
588,2020,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",3298510,Angola
462,2021,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",3258544,Angola
894,2018,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",2917948,Angola
1426,2014,São Paulo,18069000,Outros chocolates e preparações alimentícias c...,2691225,Angola
1302,2015,Não Declarada,17019900,"Outros açúcares de cana, beterraba, sacarose q...",2299569,Angola
1173,2016,Paraná,17019900,"Outros açúcares de cana, beterraba, sacarose q...",2217426,Angola
5,2024,Mato Grosso,17019900,"Outros açúcares de cana, beterraba, sacarose q...",1914447,Angola
1427,2014,São Paulo,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",1843903,Angola
1428,2014,Rio Grande do Sul,20059900,"Outros produtos hortícolas, preparados ou cons...",1791478,Angola
589,2020,Paraná,17019900,"Outros açúcares de cana, beterraba, sacarose q...",1591826,Angola
1174,2016,Rio Grande do Sul,20059900,"Outros produtos hortícolas, preparados ou cons...",1460981,Angola
1175,2016,Não Declarada,17019900,"Outros açúcares de cana, beterraba, sacarose q...",1408858,Angola
749,2019,Paraná,17019900,"Outros açúcares de cana, beterraba, sacarose q...",1378271,Angola
750,2019,Alagoas,17019900,"Outros açúcares de cana, beterraba, sacarose q...",1319072,Angola
1303,2015,Rio Grande do Sul,20059900,"Outros produtos hortícolas, preparados ou cons...",1295686,Angola
1176,2016,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",1277690,Angola
1429,2014,São Paulo,21041011,"Preparações para caldos e sopas, em embalagens...",1259733,Angola
7,2024,Goiás,17019900,"Outros açúcares de cana, beterraba, sacarose q...",1162085,Angola
1017,2017,Não Declarada,17019900,"Outros açúcares de cana, beterraba, sacarose q...",1133391,Angola
1304,2015,São Paulo,21041011,"Preparações para caldos e sopas, em embalagens...",998620,Angola
895,2018,Paraná,17019900,"Outros açúcares de cana, beterraba, sacarose q...",995910,Angola
168,2023,Minas Gerais,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",951350,Angola
464,2021,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",949686,Angola
332,2022,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",944732,Angola
1019,2017,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",940527,Angola
169,2023,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",915669,Angola
1305,2015,Alagoas,17019900,"Outros açúcares de cana, beterraba, sacarose q...",913755,Angola
170,2023,Minas Gerais,17019900,"Outros açúcares de cana, beterraba, sacarose q...",910186,Angola
1020,2017,São Paulo,21041011,"Preparações para caldos e sopas, em embalagens...",863830,Angola
1432,2014,Espírito Santo,18069000,Outros chocolates e preparações alimentícias c...,834600,Angola
1433,2014,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",818454,Angola
1178,2016,São Paulo,21041011,"Preparações para caldos e sopas, em embalagens...",794612,Angola
897,2018,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",734168,Angola
898,2018,São Paulo,21041011,"Preparações para caldos e sopas, em embalagens...",716953,Angola
899,2018,Rio Grande do Sul,20059900,"Outros produtos hortícolas, preparados ou cons...",686678,Angola
593,2020,Goiás,17019900,"Outros açúcares de cana, beterraba, sacarose q...",671677,Angola
333,2022,Minas Gerais,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",603903,Angola
594,2020,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",588273,Angola
900,2018,Paraná,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",549347,Angola
1023,2017,Paraná,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",529630,Angola
1024,2017,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",507047,Angola
1309,2015,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",487405,Angola
1436,2014,São Paulo,21069029,"Pós para preparações de cremes, sorvetes, flan...",468892,Angola
754,2019,Paraná,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",462002,Angola
1026,2017,Rio Grande do Sul,20059900,"Outros produtos hortícolas, preparados ou cons...",424942,Angola
11,2024,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",415766,Angola
1310,2015,São Paulo,18069000,Outros chocolates e preparações alimentícias c...,391300,Angola
1311,2015,Sergipe,17019900,"Outros açúcares de cana, beterraba, sacarose q...",374962,Angola
334,2022,Goiás,17019900,"Outros açúcares de cana, beterraba, sacarose q...",371795,Angola
1437,2014,Minas Gerais,18069000,Outros chocolates e preparações alimentícias c...,369027,Angola
1438,2014,São Paulo,21039021,"Condimentos e temperos, compostos, em embalage...",360748,Angola
755,2019,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",359771,Angola
1180,2016,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",349201,Angola
1312,2015,São Paulo,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",346415,Angola
1027,2017,Minas Gerais,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",343655,Angola
756,2019,São Paulo,21041011,"Preparações para caldos e sopas, em embalagens...",337084,Angola
335,2022,São Paulo,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",310124,Angola
1182,2016,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",292300,Angola
1441,2014,Minas Gerais,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",272010,Angola
177,2023,São Paulo,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",271975,Angola
466,2021,Rio Grande do Sul,20059900,"Outros produtos hortícolas, preparados ou cons...",267180,Angola
1029,2017,São Paulo,18069000,Outros chocolates e preparações alimentícias c...,247752,Angola
904,2018,Não Declarada,17019900,"Outros açúcares de cana, beterraba, sacarose q...",235347,Angola
1183,2016,Espírito Santo,17019900,"Outros açúcares de cana, beterraba, sacarose q...",234214,Angola
1315,2015,São Paulo,21069029,"Pós para preparações de cremes, sorvetes, flan...",217004,Angola
469,2021,Minas Gerais,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",202980,Angola
905,2018,Minas Gerais,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",194613,Angola
595,2020,Paraná,18069000,Outros chocolates e preparações alimentícias c...,191730,Angola
1444,2014,Rio Grande do Sul,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",187130,Angola
15,2024,São Paulo,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",180834,Angola
1445,2014,São Paulo,19041000,"Produtos à base de cereais, obtidos por expans...",179541,Angola
596,2020,Paraná,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",170595,Angola
1318,2015,São Paulo,21039021,"Condimentos e temperos, compostos, em embalage...",168747,Angola
1319,2015,Minas Gerais,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",162742,Angola
1031,2017,Espírito Santo,18069000,Outros chocolates e preparações alimentícias c...,162639,Angola
1185,2016,Goiás,19041000,"Produtos à base de cereais, obtidos por expans...",159724,Angola
18,2024,São Paulo,21039029,"Outros condimentos e temperos, compostos",148322,Angola
906,2018,São Paulo,18069000,Outros chocolates e preparações alimentícias c...,147143,Angola
1320,2015,Espírito Santo,18069000,Outros chocolates e preparações alimentícias c...,141449,Angola
1187,2016,São Paulo,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",140048,Angola
1189,2016,São Paulo,20098990,"Sucos (sumo) de outras frutas, não fermentado,...",138428,Angola
1190,2016,São Paulo,18069000,Outros chocolates e preparações alimentícias c...,138031,Angola
21,2024,Espírito Santo,18050000,"Cacau em pó, sem adição de açúcar ou outros ed...",133960,Angola
760,2019,Rio Grande do Norte,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",132948,Angola
471,2021,São Paulo,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",132759,Angola
341,2022,Rio Grande do Sul,20059900,"Outros produtos hortícolas, preparados ou cons...",130658,Angola
1321,2015,São Paulo,19041000,"Produtos à base de cereais, obtidos por expans...",125429,Angola
342,2022,Paraná,21069010,Outras preparações para elaboração de bebidas,120304,Angola
1192,2016,São Paulo,21039021,"Condimentos e temperos, compostos, em embalage...",118964,Angola
762,2019,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",117180,Angola
24,2024,Minas Gerais,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",115088,Angola
344,2022,São Paulo,21041011,"Preparações para caldos e sopas, em embalagens...",106844,Angola
1322,2015,Rio Grande do Sul,18069000,Outros chocolates e preparações alimentícias c...,99066,Angola
763,2019,Paraná,18069000,Outros chocolates e preparações alimentícias c...,95478,Angola
346,2022,São Paulo,18069000,Outros chocolates e preparações alimentícias c...,94306,Angola
598,2020,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",92080,Angola
907,2018,São Paulo,21039021,"Condimentos e temperos, compostos, em embalage...",91840,Angola
476,2021,Goiás,17019900,"Outros açúcares de cana, beterraba, sacarose q...",89285,Angola
765,2019,Rio Grande do Sul,17019900,"Outros açúcares de cana, beterraba, sacarose q...",84700,Angola
599,2020,São Paulo,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",84047,Angola
1448,2014,Rio Grande do Norte,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",82987,Angola
184,2023,São Paulo,18069000,Outros chocolates e preparações alimentícias c...,82336,Angola
908,2018,São Paulo,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",81907,Angola
1449,2014,Espírito Santo,12119090,"Outras plantas e partes, para perfumaria, medi...",78973,Angola
909,2018,Alagoas,17019900,"Outros açúcares de cana, beterraba, sacarose q...",78357,Angola
1326,2015,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",77490,Angola
1450,2014,São Paulo,21069010,Outras preparações para elaboração de bebidas,77019,Angola
600,2020,Minas Gerais,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",74592,Angola
477,2021,São Paulo,18069000,Outros chocolates e preparações alimentícias c...,74386,Angola
601,2020,Rio Grande do Norte,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",72636,Angola
767,2019,São Paulo,18069000,Outros chocolates e preparações alimentícias c...,68383,Angola
768,2019,Minas Gerais,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",68306,Angola
351,2022,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",67375,Angola
1452,2014,São Paulo,19019090,"Outras preparações alimentícias de farinhas, e...",67185,Angola
1033,2017,São Paulo,21039021,"Condimentos e temperos, compostos, em embalage...",64060,Angola
479,2021,Pernambuco,17019900,"Outros açúcares de cana, beterraba, sacarose q...",61425,Angola
352,2022,São Paulo,12119090,"Outras plantas e partes, para perfumaria, medi...",60086,Angola
187,2023,Paraná,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",57304,Angola
1454,2014,Goiás,9041200,"Pimenta (do gênero Piper), triturada ou em pó",56790,Angola
911,2018,São Paulo,21021090,Outras leveduras vivas,56679,Angola
1035,2017,São Paulo,21069029,"Pós para preparações de cremes, sorvetes, flan...",54500,Angola
771,2019,São Paulo,20098990,"Sucos (sumo) de outras frutas, não fermentado,...",54128,Angola
1195,2016,Goiás,17019900,"Outros açúcares de cana, beterraba, sacarose q...",53732,Angola
1196,2016,São Paulo,21023000,"Pós para levedar, preparados",52333,Angola
1197,2016,Espírito Santo,18069000,Outros chocolates e preparações alimentícias c...,52325,Angola
481,2021,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",52164,Angola
1327,2015,Alagoas,20098990,"Sucos (sumo) de outras frutas, não fermentado,...",49680,Angola
912,2018,São Paulo,20098990,"Sucos (sumo) de outras frutas, não fermentado,...",48643,Angola
188,2023,Paraná,21069029,"Pós para preparações de cremes, sorvetes, flan...",47487,Angola
913,2018,Rio Grande do Norte,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",47040,Angola
1457,2014,Alagoas,20098990,"Sucos (sumo) de outras frutas, não fermentado,...",46805,Angola
1458,2014,São Paulo,20052000,"Batatas, preparados ou conservados, exceto em ...",46493,Angola
189,2023,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",45253,Angola
916,2018,Paraná,21069029,"Pós para preparações de cremes, sorvetes, flan...",45248,Angola
355,2022,São Paulo,20098990,"Sucos (sumo) de outras frutas, não fermentado,...",44996,Angola
917,2018,Ceará,20098990,"Sucos (sumo) de outras frutas, não fermentado,...",44289,Angola
773,2019,Paraná,21069029,"Pós para preparações de cremes, sorvetes, flan...",44241,Angola
1200,2016,São Paulo,19041000,"Produtos à base de cereais, obtidos por expans...",44028,Angola
356,2022,São Paulo,21069010,Outras preparações para elaboração de bebidas,43867,Angola
774,2019,São Paulo,21039021,"Condimentos e temperos, compostos, em embalage...",43826,Angola
1329,2015,São Paulo,19019090,"Outras preparações alimentícias de farinhas, e...",43189,Angola
775,2019,São Paulo,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",41895,Angola
28,2024,Paraná,19019090,"Outras preparações alimentícias de farinhas, e...",41040,Angola
1203,2016,São Paulo,21069010,Outras preparações para elaboração de bebidas,40485,Angola
1039,2017,São Paulo,21023000,"Pós para levedar, preparados",39067,Angola
918,2018,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",39060,Angola
29,2024,São Paulo,21069029,"Pós para preparações de cremes, sorvetes, flan...",38951,Angola
919,2018,São Paulo,21069029,"Pós para preparações de cremes, sorvetes, flan...",38533,Angola
778,2019,Minas Gerais,18069000,Outros chocolates e preparações alimentícias c...,38495,Angola
1460,2014,Pará,20098990,"Sucos (sumo) de outras frutas, não fermentado,...",38357,Angola
1461,2014,São Paulo,21041019,Outras preparações para caldos e sopas,37818,Angola
359,2022,Goiás,19041000,"Produtos à base de cereais, obtidos por expans...",36369,Angola
487,2021,Rio Grande do Sul,18069000,Outros chocolates e preparações alimentícias c...,35935,Angola
920,2018,São Paulo,21023000,"Pós para levedar, preparados",35136,Angola
193,2023,Rio Grande do Sul,18069000,Outros chocolates e preparações alimentícias c...,34952,Angola
1041,2017,Goiás,19041000,"Produtos à base de cereais, obtidos por expans...",34821,Angola
360,2022,Rio Grande do Sul,21069010,Outras preparações para elaboração de bebidas,34560,Angola
488,2021,Paraná,21069029,"Pós para preparações de cremes, sorvetes, flan...",34042,Angola
1462,2014,Goiás,21041011,"Preparações para caldos e sopas, em embalagens...",33926,Angola
361,2022,Rio Grande do Sul,18069000,Outros chocolates e preparações alimentícias c...,32995,Angola
922,2018,São Paulo,19030000,Tapioca e seus sucedâneos preparados a partir ...,32928,Angola
1206,2016,Pará,1012900,"Cavalos, exceto reprodutores de raça pura",30439,Angola
1463,2014,Santa Catarina,21069029,"Pós para preparações de cremes, sorvetes, flan...",30415,Angola
362,2022,Paraná,21069029,"Pós para preparações de cremes, sorvetes, flan...",30359,Angola
33,2024,Rio Grande do Sul,21039021,"Condimentos e temperos, compostos, em embalage...",29892,Angola
490,2021,São Paulo,21069010,Outras preparações para elaboração de bebidas,29400,Angola
363,2022,Alagoas,8011100,"Cocos, frescos ou secos, dessecados",29308,Angola
780,2019,São Paulo,21069010,Outras preparações para elaboração de bebidas,28410,Angola
1043,2017,São Paulo,19019090,"Outras preparações alimentícias de farinhas, e...",27552,Angola
1044,2017,Minas Gerais,21039021,"Condimentos e temperos, compostos, em embalage...",27271,Angola
613,2020,Alagoas,8011100,"Cocos, frescos ou secos, dessecados",27026,Angola
34,2024,São Paulo,19019090,"Outras preparações alimentícias de farinhas, e...",25961,Angola
928,2018,Rio Grande do Sul,18069000,Outros chocolates e preparações alimentícias c...,25266,Angola
197,2023,Rio Grande do Sul,21069010,Outras preparações para elaboração de bebidas,23831,Angola
930,2018,Goiás,19041000,"Produtos à base de cereais, obtidos por expans...",22800,Angola
365,2022,Rio Grande do Sul,21021090,Outras leveduras vivas,22761,Angola
931,2018,Minas Gerais,21039021,"Condimentos e temperos, compostos, em embalage...",22644,Angola
616,2020,São Paulo,18069000,Outros chocolates e preparações alimentícias c...,22562,Angola
784,2019,São Paulo,21069029,"Pós para preparações de cremes, sorvetes, flan...",22303,Angola

In [9]:
sp = df[(df['Países'] == 'Angola') &
        (df['UF do Produto'] == 'São Paulo') &
        (df['Ano'] == 2014)]

sp[['Ano', 'Países', 'Código NCM', 'Descrição NCM', 'UF do Produto', 'Valor US$ FOB']] \
    .sort_values(['Código NCM', 'Valor US$ FOB'], ascending=[True, False])

,Ano,Países,Código NCM,Descrição NCM,UF do Produto,Valor US$ FOB
1489,2014,Angola,1012900,"Cavalos, exceto reprodutores de raça pura",São Paulo,6000
1525,2014,Angola,9041100,"Pimenta (do gênero Piper), não triturada nem e...",São Paulo,1199
1469,2014,Angola,9041200,"Pimenta (do gênero Piper), triturada ou em pó",São Paulo,17774
1499,2014,Angola,9062000,"Canela e flores de caneleira, trituradas ou em pó",São Paulo,4100
1552,2014,Angola,9071000,"Cravo-da-índia (frutos, flores e pedúnculos), ...",São Paulo,129
1549,2014,Angola,9101200,"Gengibre, triturado ou em pó",São Paulo,212
1486,2014,Angola,9109900,Outras especiarias,São Paulo,8244
1547,2014,Angola,11029000,Farinha de outros cereais,São Paulo,283
1472,2014,Angola,11041200,"Grãos de aveia, esmagados ou em flocos",São Paulo,16077
1474,2014,Angola,11081200,Amido de milho,São Paulo,13217
1516,2014,Angola,12040090,"Outras sementes de linho (linhaça), mesmo trit...",São Paulo,1789
1502,2014,Angola,12119010,"Orégano (Origanum vulgare) fresco ou seco, par...",São Paulo,3250
1465,2014,Angola,12119090,"Outras plantas e partes, para perfumaria, medi...",São Paulo,22243
1497,2014,Angola,17019100,"Outros açúcares de cana, beterraba, com aromat...",São Paulo,4615
1418,2014,Angola,17019900,"Outros açúcares de cana, beterraba, sacarose q...",São Paulo,128569913
1427,2014,Angola,17049020,"Caramelos, confeitos, dropes, pastilhas, e pro...",São Paulo,1843903
1523,2014,Angola,18050000,"Cacau em pó, sem adição de açúcar ou outros ed...",São Paulo,1298
1481,2014,Angola,18061000,"Cacau em pó, com adição de açúcar ou outros ed...",São Paulo,10468
1426,2014,Angola,18069000,Outros chocolates e preparações alimentícias c...,São Paulo,2691225
1452,2014,Angola,19019090,"Outras preparações alimentícias de farinhas, e...",São Paulo,67185
1483,2014,Angola,19023000,Outras massas alimentícias,São Paulo,9711
1495,2014,Angola,19030000,Tapioca e seus sucedâneos preparados a partir ...,São Paulo,4807
1445,2014,Angola,19041000,"Produtos à base de cereais, obtidos por expans...",São Paulo,179541
1458,2014,Angola,20052000,"Batatas, preparados ou conservados, exceto em ...",São Paulo,46493
1470,2014,Angola,20059900,"Outros produtos hortícolas, preparados ou cons...",São Paulo,17590
1498,2014,Angola,20098990,"Sucos (sumo) de outras frutas, não fermentado,...",São Paulo,4349
1517,2014,Angola,21021090,Outras leveduras vivas,São Paulo,1772
1511,2014,Angola,21023000,"Pós para levedar, preparados",São Paulo,2165
1438,2014,Angola,21039021,"Condimentos e temperos, compostos, em embalage...",São Paulo,360748
1514,2014,Angola,21039029,"Outros condimentos e temperos, compostos",São Paulo,1907
1429,2014,Angola,21041011,"Preparações para caldos e sopas, em embalagens...",São Paulo,1259733
1461,2014,Angola,21041019,Outras preparações para caldos e sopas,São Paulo,37818
1450,2014,Angola,21069010,Outras preparações para elaboração de bebidas,São Paulo,77019
1533,2014,Angola,21069021,"Pós para a fabricação de pudins, em embalagens...",São Paulo,897
1436,2014,Angola,21069029,"Pós para preparações de cremes, sorvetes, flan...",São Paulo,468892
1519,2014,Angola,28363000,Hidrogenocarbonato (bicarbonato) de sódio,São Paulo,1488
1558,2014,Angola,35030019,Outras gelatinas e seus derivados,São Paulo,37

In [11]:
df.describe()

               Ano    Código NCM  Valor US$ FOB
count  1576.000000  1.576000e+03   1.576000e+03
mean   2019.121827  1.739008e+07   8.043860e+05
std       3.219446  4.433882e+06   7.347810e+06
min    2014.000000  1.012900e+06   0.000000e+00
25%    2016.000000  1.701990e+07   3.822500e+02
50%    2019.000000  1.806900e+07   2.688500e+03
75%    2022.000000  2.009899e+07   2.541100e+04
max    2024.000000  3.503002e+07   1.360277e+08

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1576 entries, 0 to 1575
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Ano            1576 non-null   int64
 1   Países         1576 non-null   object
 2   Código NCM     1576 non-null   int64
 3   Descrição NCM  1576 non-null   object
 4   UF do Produto  1576 non-null   object
 5   Valor US$ FOB  1576 non-null   int64
dtypes: int64(3), object(3)
memory usage: 74.0+ KB