In [4]:
pip install wbgapi

Requirement already satisfied: wbgapi in /usr/local/lib/python3.12/dist-packages (1.0.14)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from wbgapi) (2.32.4)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from wbgapi) (6.0.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from wbgapi) (0.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->wbgapi) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->wbgapi) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->wbgapi) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->wbgapi) (2026.2.25)

In [3]:
import wbgapi as wb
import pandas as pd

# 1. Definir os países (PALOP)
palop = ['AGO', 'CPV', 'GNB', 'MOZ', 'STP', 'GNQ']

# 2. Definir o indicador do PIB per capita
indicator = 'NY.GDP.PCAP.CD'

# 3. Consumir a API definindo o intervalo de anos (range)
# O parâmetro 'time' aceita um range de anos
df_pib_longo = wb.data.DataFrame(indicator, palop, time=range(2010, 2026))

# Limpar o DataFrame
df_pib_longo = df_pib_longo.reset_index()

# Visualizar o resultado
print(df_pib_longo)

  economy        YR2010        YR2011        YR2012        YR2013  \
0     AGO   4101.637156   5184.152691   5702.453063   5688.579162
1     CPV   3579.460061   4002.013869   3736.815170   3960.975968
2     GNB    600.194299    719.539573    635.461653    654.304534
3     GNQ  13720.165872  17198.213667  17308.572392  16304.071320
4     MOZ    496.185839    618.176493    685.685748    686.505673
5     STP   1045.209582   1219.801891   1192.020291   1382.575784

         YR2014       YR2015       YR2016       YR2017       YR2018  \
0   5649.687625  3641.728939  2051.814621  2790.718869  2860.093648
1   3985.607065  3415.062667  3608.966052  3893.095714  4294.965100
2    652.022501   645.066837   679.665387   783.123187   808.531613
3  15548.662466  9068.910032  7453.197979  7809.104657  8102.470848
4    697.142680   610.563775   441.489735   470.938563   517.507260
5   1489.676334  1298.109466  1434.870181  1555.794778  1825.599718

        YR2019       YR2020       YR2021       YR2022       YR2023  \
0  2493.678844  1759.356199  2303.908127  3682.113151  2916.136633
1  4380.781173  3539.226612  3971.444092  4323.313620  4794.901219
2   811.216426   846.915856   926.780921   883.199131   988.087886
3  6804.149231  5764.055029  6945.630698  7589.299649  6677.793435
4   519.092551   462.433876   509.907829   578.251664   622.000298
5  1935.293182  2167.220018  2362.588272  2389.737298  2990.660614

        YR2024  YR2025
0  2665.874448     NaN
1  5192.481573     NaN
2  1007.741517     NaN
3  6745.400132     NaN
4   656.776825     NaN
5  3490.568835     NaN

População

In [19]:
import wbgapi as wb

# 1. Definir os países e o indicador de população
paises = ['AGO', 'CPV', 'GNB', 'MOZ', 'STP', 'GNQ']
pop_indicator = 'SP.POP.TOTL'

# 2. Baixar os dados (de 2010 a 2025 para bater com o seu IDH)
df_pop = wb.data.DataFrame(pop_indicator, paises, time=range(2010, 2026))

# 3. Organizar o DataFrame da população (formato longo)
df_pop = df_pop.stack().reset_index()
df_pop.columns = ['iso_code', 'ano', 'populacao_total']

# 4. Limpar o campo 'ano' (remover o 'YR' que a API coloca)
df_pop['ano'] = df_pop['ano'].str.replace('YR', '').astype(int)

display(df_pop.head())

  iso_code   ano  populacao_total
0      AGO  2010       23294825.0
1      AGO  2011       24218352.0
2      AGO  2012       25177394.0
3      AGO  2013       26165620.0
4      AGO  2014       27160769.0

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
import pandas as pd
import json

path = "/content/drive/MyDrive/TCC/dados_HDI/hdr-data.json"

with open(path, 'r', encoding='utf-8') as f:
    dados_json = json.load(f)

df = pd.DataFrame(dados_json)

df_limpo = df[['countryIsoCode', 'country', 'indicatorCode', 'indicator', 'year', 'actualValue']].copy()
df_limpo.columns = ['iso_code', 'pais', 'id_indicador', 'nome_indicador', 'ano', 'valor_real']

path_saida = "/content/drive/MyDrive/TCC/dados_HDI/dados_hdi_palop.csv"
df_limpo.to_csv(path_saida, index=False, encoding='utf-8-sig')

print(f"Sucesso! O arquivo foi transformado e salvo em: {path_saida}")

Sucesso! O arquivo foi transformado e salvo em: /content/drive/MyDrive/TCC/dados_HDI/dados_hdi_palop.csv

In [20]:
import pandas as pd

df_hdi = df.dropna(subset=['countryIsoCode'])

df_hdi['actualValue'] = pd.to_numeric(df_hdi['actualValue'], errors='coerce')

df_features = df_hdi.pivot_table(
    index=['countryIsoCode', 'country', 'year'],
    columns='indicatorCode',
    values='actualValue'
).reset_index()

df_features.columns = ['iso_code', 'pais', 'ano', 'renda_nacional', 'expectativa_vida']

display(df_features.head())

  iso_code    pais   ano  renda_nacional  expectativa_vida
0      AGO  Angola  2010     8754.559189            57.242
1      AGO  Angola  2011     8707.882020            58.093
2      AGO  Angola  2012     9194.230072            58.916
3      AGO  Angola  2013     9423.771811            59.705
4      AGO  Angola  2014     9694.499032            60.396